verbose = "info"
no_progress = true
offline = true
max_cache_age = "7d"

exclude = [
  "^mailto:",
  "^https?://localhost",
  "^https?://127\\.0\\.0\\.1"
]

exclude_path = [
  "(^|/)node_modules(/|$)",
  "(^|/)\\.venv(/|$)"
]
