from __future__ import annotations

from typing import Any, Callable, Protocol


class RouterState(Protocol):
    track: str | None
    current_index: int


class RouterNavigator(Protocol):
    def show_start_screen(self) -> None: ...

    def show_candidate_info(self) -> None: ...

    def show_trait_screen_by_trait_id(self, flow_idx: int, trait: dict[str, str]) -> None: ...

    def show_custom_question_item_screen(self, flow_idx: int, custom_question: dict[str, str]) -> None: ...

    def open_settings(self) -> None: ...

    def open_question_editor(self) -> None: ...

    def show_keyboard_shortcuts_help(self) -> None: ...


class RouterRenderer(Protocol):
    def bind_all(self, key_combo: str, callback: Callable[[Any], str | None]) -> None: ...

    def footer_action(self, label: str) -> Callable[[], None] | None: ...


class RouterFlowState(Protocol):
    def state(self) -> RouterState: ...

    def flow_len(self) -> int: ...

    def flow_item(self, index: int) -> dict[str, str] | None: ...

    def mark_flow_timestamp(self, flow_index: int) -> None: ...

    def start_question_recording_for_flow(self, flow_index: int) -> None: ...

    def trait_by_id(self, trait_id: str) -> dict[str, str] | None: ...

    def custom_by_id(self, custom_id: str) -> dict[str, str] | None: ...

    def build_active_flow(self, track: str) -> None: ...
