from __future__ import annotations

from ui_composition import (
    GROUP_ID_PATTERN,
    PREFIXED_TRAIT_ID_ALIAS_PATTERN,
    RUNTIME_TRAIT_ID_PATTERN,
    SIGNAL_ID_PATTERN,
    TRAIT_FILE_PATTERN,
    TRAIT_ID_ALIAS_PATTERN,
    QuestionRuntimeDefinitionService,
    RuntimeSignalDefinition,
    RuntimeSignalGroup,
    RuntimeSignalRecord,
    build_runtime_trait_id,
    default_runtime_definition,
    ensure_valid_trait_id,
    list_signal_refs,
    next_trait_id,
    normalize_runtime_definition,
    normalize_runtime_group,
    normalize_runtime_signal,
    runtime_trait_id_for_rubric_trait,
    runtime_trait_id_prefix,
    slugify_trait_name,
)

__all__ = [
    "GROUP_ID_PATTERN",
    "PREFIXED_TRAIT_ID_ALIAS_PATTERN",
    "RUNTIME_TRAIT_ID_PATTERN",
    "SIGNAL_ID_PATTERN",
    "TRAIT_FILE_PATTERN",
    "TRAIT_ID_ALIAS_PATTERN",
    "QuestionRuntimeDefinitionService",
    "RuntimeSignalDefinition",
    "RuntimeSignalGroup",
    "RuntimeSignalRecord",
    "build_runtime_trait_id",
    "default_runtime_definition",
    "ensure_valid_trait_id",
    "list_signal_refs",
    "next_trait_id",
    "normalize_runtime_definition",
    "normalize_runtime_group",
    "normalize_runtime_signal",
    "runtime_trait_id_for_rubric_trait",
    "runtime_trait_id_prefix",
    "slugify_trait_name",
]
