from __future__ import annotations

from scoring_reporting import (
    CANONICAL_SIGNAL_COMPARISON_KEYS,
    DEFAULT_EXTENDED_GROUP_LABEL,
    CanonicalSignal,
    CanonicalSignalGroup,
    CanonicalSignalGroupRecord,
    CanonicalSignalRecord,
    _comparison_view,
    _group_id_from_label,
    _normalize_explicit_extended_groups,
    _normalize_runtime_extended_signals,
    _normalize_signal_collection,
    _runtime_extended_group_label,
    build_signal_dictionary_index,
    iter_trait_schema_signals,
    normalize_core_signals,
    normalize_extended_signal_groups,
    normalize_trait_signal,
    resolve_trait_signal_label,
    resolve_trait_signal_runtime_id,
    resolve_trait_signal_selection_id,
    resolve_trait_signal_weight,
    signal_selection_aliases,
)

__all__ = [
    "CANONICAL_SIGNAL_COMPARISON_KEYS",
    "DEFAULT_EXTENDED_GROUP_LABEL",
    "CanonicalSignal",
    "CanonicalSignalGroup",
    "CanonicalSignalGroupRecord",
    "CanonicalSignalRecord",
    "_comparison_view",
    "_group_id_from_label",
    "_normalize_explicit_extended_groups",
    "_normalize_runtime_extended_signals",
    "_normalize_signal_collection",
    "_runtime_extended_group_label",
    "build_signal_dictionary_index",
    "iter_trait_schema_signals",
    "normalize_core_signals",
    "normalize_extended_signal_groups",
    "normalize_trait_signal",
    "resolve_trait_signal_label",
    "resolve_trait_signal_runtime_id",
    "resolve_trait_signal_selection_id",
    "resolve_trait_signal_weight",
    "signal_selection_aliases",
]
